/*
 * -----LICENSE START-----
 * JSHManager - A Java-based tool for managing one's ScoreHero account.
 * Copyright (C) 2008 Tim Mullin
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * -----LICENSE END-----
*/
/*
 * CheckUpdatesDialog.java
 *
 * Created on October 7, 2008, 7:34 PM
 */

package jshm.gui;

import java.awt.Color;

import javax.swing.SwingWorker;

import jshm.JSHManager;
import jshm.UpdateChecker;
import jshm.gui.components.EscapeableDialog;
import jshm.util.Util;

/**
 *
 * @author  Tim
 */
public class CheckUpdatesDialog extends EscapeableDialog {
	UpdateChecker.Info info = null;
	Color defaultLabelFg = null,
		runningLatestFg = new Color(0x009900),
		errorFg = new Color(0x990000),
		runningOldFg = new Color(0xFF6600);
	
	public CheckUpdatesDialog() {
		this(null, true);
	}
	
    /** Creates new form CheckUpdatesDialog */
    public CheckUpdatesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        defaultLabelFg = statusLabel.getForeground();
        checkForUpdates(true);
    }
    
    private void checkForUpdates(final boolean useCache) {
		downloadLink.setVisible(false);
		pack();
		statusLabel.setForeground(defaultLabelFg);
		statusLabel.setText("Checking for updates...");
		
    	new SwingWorker<Void, Void>() {
			protected Void doInBackground() throws Exception {
				info = UpdateChecker.getInfo(useCache);
				return null;
			}
			
			public void done() {				
				if (null == info) {
					statusLabel.setForeground(errorFg);
					statusLabel.setText("Unable to retrieve update data.");
					latestVersionField.setText("Unknown");
					return;
				}
				
				latestVersionField.setText(info.latestVersion);
				int versionComp = Util.versionCompare(JSHManager.Version.VERSION, info.latestVersion);
				
				if (versionComp < 0 || (versionComp == 0 && JSHManager.Version.IS_BETA)) {
					statusLabel.setForeground(runningOldFg);
					statusLabel.setText("A newer version is available.");
					downloadLink.setToolTipText(info.getUpdateUrl());
					downloadLink.setVisible(true);
					pack();
				} else if (versionComp > 0 || JSHManager.Version.IS_BETA) {
					statusLabel.setText("You are running a beta version.");
				} else {
					statusLabel.setForeground(runningLatestFg);
					statusLabel.setText("You are running the latest version.");
				}
			}
    	}.execute();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        installedVersionField = new javax.swing.JTextField();
        latestVersionField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        linkPanel = new javax.swing.JPanel();
        downloadLink = new jshm.gui.components.Hyperlink();
        buttonPanel = new javax.swing.JPanel();
        checkButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Installed version:");

        jLabel2.setText("Latest version:");

        installedVersionField.setEditable(false);
        installedVersionField.setText(jshm.JSHManager.Version.STRING);

        latestVersionField.setEditable(false);
        latestVersionField.setText("Unknown");

        statusLabel.setFont(statusLabel.getFont().deriveFont(statusLabel.getFont().getSize()+4f));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Checking for updates...");

        linkPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        downloadLink.setText("Download");
        downloadLink.setFont(downloadLink.getFont().deriveFont(downloadLink.getFont().getSize()+3f));
        downloadLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadLinkActionPerformed(evt);
            }
        });
        linkPanel.add(downloadLink);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        checkButton.setText("Refresh");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(checkButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(latestVersionField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(installedVersionField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(installedVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(latestVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
	checkForUpdates(false);
}//GEN-LAST:event_checkButtonActionPerformed

private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
	dispose();
}//GEN-LAST:event_closeButtonActionPerformed

private void downloadLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadLinkActionPerformed
	assert info != null;
	Util.openURL(info.getUpdateUrl());
}//GEN-LAST:event_downloadLinkActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckUpdatesDialog dialog = new CheckUpdatesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton closeButton;
    private jshm.gui.components.Hyperlink downloadLink;
    private javax.swing.JTextField installedVersionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField latestVersionField;
    private javax.swing.JPanel linkPanel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

}
