/*
 * CheckUpdatesDialog.java
 *
 * Created on October 7, 2008, 7:34 PM
 */

package jshm.gui;

import java.awt.Color;

import javax.swing.SwingWorker;

import jshm.JSHManager;
import jshm.UpdateChecker;
import jshm.util.Util;

/**
 *
 * @author  Tim
 */
public class CheckUpdatesDialog extends javax.swing.JDialog {
	UpdateChecker.Info info = null;
	Color defaultLabelFg = null,
		runningLatestFg = new Color(0x009900),
		errorFg = new Color(0x990000),
		runningOldFg = new Color(0xFF6600);
	
	public CheckUpdatesDialog() {
		this(null, true);
	}
	
    /** Creates new form CheckUpdatesDialog */
    public CheckUpdatesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        defaultLabelFg = statusLabel.getForeground();
        checkForUpdates();
    }
    
    private void checkForUpdates() {
		downloadLink.setVisible(false);
		statusLabel.setForeground(defaultLabelFg);
		statusLabel.setText("Checking for updates...");
		
    	new SwingWorker<Void, Void>() {
			protected Void doInBackground() throws Exception {
				info = UpdateChecker.getInfo(true);
				return null;
			}
			
			public void done() {				
				if (null == info) {
					statusLabel.setForeground(errorFg);
					statusLabel.setText("Unable to retrieve update data.");
					return;
				}
				
				latestVersionField.setText(info.latestVersion);
				int versionComp = Util.versionCompare(JSHManager.Version.VERSION, info.latestVersion);
				
				if (versionComp < 0) {
					statusLabel.setForeground(runningOldFg);
					statusLabel.setText("A newer version is available.");
					downloadLink.setVisible(true);
				} else if (versionComp > 0) {
					statusLabel.setText("You are running a beta version.");
				} else {
					statusLabel.setForeground(runningLatestFg);
					statusLabel.setText("You are running the latest version.");
				}
			}
    	}.execute();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        installedVersionField = new javax.swing.JTextField();
        latestVersionField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        linkPanel = new javax.swing.JPanel();
        downloadLink = new org.jdesktop.swingx.JXHyperlink();
        jPanel1 = new javax.swing.JPanel();
        checkButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Installed version:");

        jLabel2.setText("Latest version:");

        installedVersionField.setEditable(false);
        installedVersionField.setText(jshm.JSHManager.Version.STRING);

        latestVersionField.setEditable(false);
        latestVersionField.setText("Unknown");

        statusLabel.setFont(statusLabel.getFont().deriveFont(statusLabel.getFont().getSize()+4f));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Checking for updates...");

        linkPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        downloadLink.setText("Download");
        downloadLink.setDefaultCapable(false);
        downloadLink.setFont(downloadLink.getFont().deriveFont(downloadLink.getFont().getSize()+3f));
        downloadLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadLinkActionPerformed(evt);
            }
        });
        linkPanel.add(downloadLink);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        checkButton.setText("Check for Updates");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(checkButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(latestVersionField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(installedVersionField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(installedVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(latestVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void downloadLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadLinkActionPerformed
	assert info != null;
	
	String url = info.versions.get(0).url;
	Util.openURL(url);
}//GEN-LAST:event_downloadLinkActionPerformed

private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
	checkForUpdates();
}//GEN-LAST:event_checkButtonActionPerformed

private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
	dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckUpdatesDialog dialog = new CheckUpdatesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JButton closeButton;
    private org.jdesktop.swingx.JXHyperlink downloadLink;
    private javax.swing.JTextField installedVersionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField latestVersionField;
    private javax.swing.JPanel linkPanel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

}
