/*
 * -----LICENSE START-----
 * JSHManager - A Java-based tool for managing one's ScoreHero account.
 * Copyright (C) 2008 Tim Mullin
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * -----LICENSE END-----
*/
/*
 * ScoreEditorPanel.java
 *
 * Created on August 25, 2008, 1:16 AM
 */

package jshm.gui;

import jshm.gh.GhScore;
import jshm.gui.editors.GhMyScoresRatingEditor;

/**
 *
 * @author  Tim
 */
public class ScoreEditorPanel extends javax.swing.JPanel {

    /** Creates new form ScoreEditorPanel */
    public ScoreEditorPanel() {
        initComponents();
    }

	@Override
	public void setEnabled(boolean b) {
		super.setEnabled(b);
		songCombo.setEnabled(b);
		scoreField.setEditable(b);
		ratingCombo.setEnabled(b);
		percentField.setEditable(b);
		streakField.setEditable(b);
		commentField.setEditable(b);
		imageUrlField.setEditable(b);
		videoUrlField.setEditable(b);
	}
	
	public void setScore(final GhScore score) {
		if (null != score) {
			switch (score.getStatus()) {
				case NEW:
				case TEMPLATE:
					setEnabled(true); break;
					
				default:
					setEnabled(false); break;
			}
			
			imageUrlOpenButton.setEnabled(true);
			videoUrlOpenButton.setEnabled(true);
		} else {
			setEnabled(false);
			imageUrlOpenButton.setEnabled(false);
			videoUrlOpenButton.setEnabled(false);
		}
		
		songCombo.setSelectedItem(null != score ? score.getSong().getTitle() : "");
		scoreField.setText(null != score ? String.valueOf(score.getScore()) : "");
		ratingCombo.setSelectedItem(null != score ? score.getRatingIcon(true) : GhScore.getRatingIcon(0));
		percentField.setText(null != score ? String.valueOf((int) (score.getHitPercent() * 100)) : "");
		streakField.setText(null != score ? String.valueOf(score.getStreak()) : "");
		commentField.setText(null != score ? score.getComment() : "");
		imageUrlField.setText(null != score ? score.getImageUrl() : "");
		videoUrlField.setText(null != score ? score.getVideoUrl() : "");
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreField = new javax.swing.JTextField();
        ratingCombo = GhMyScoresRatingEditor.createRatingComboBox();
        percentField = new javax.swing.JTextField();
        streakField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        commentField = new javax.swing.JTextField();
        imageUrlField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        videoUrlField = new javax.swing.JTextField();
        songCombo = new javax.swing.JComboBox();
        imageUrlOpenButton = new javax.swing.JButton();
        videoUrlOpenButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        scoreField.setEditable(false);

        ratingCombo.setEnabled(false);

        percentField.setEditable(false);

        streakField.setEditable(false);

        jLabel1.setLabelFor(commentField);
        jLabel1.setText("Comment:");

        jLabel2.setLabelFor(imageUrlField);
        jLabel2.setText("Image URL:");

        commentField.setEditable(false);

        imageUrlField.setEditable(false);

        jLabel3.setLabelFor(videoUrlField);
        jLabel3.setText("Video URL:");

        videoUrlField.setEditable(false);

        songCombo.setEditable(true);
        songCombo.setEnabled(false);

        imageUrlOpenButton.setText("Open...");
        imageUrlOpenButton.setToolTipText("Open the Image URL in an external browser window");
        imageUrlOpenButton.setEnabled(false);
        imageUrlOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageUrlOpenButtonActionPerformed(evt);
            }
        });

        videoUrlOpenButton.setText("Open...");
        videoUrlOpenButton.setToolTipText("Open the Video URL in an external browser window");
        videoUrlOpenButton.setEnabled(false);
        videoUrlOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoUrlOpenButtonActionPerformed(evt);
            }
        });

        jLabel4.setLabelFor(songCombo);
        jLabel4.setText("Song:");

        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        newButton.setText("New");
        newButton.setEnabled(false);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        jLabel5.setLabelFor(scoreField);
        jLabel5.setText("Score:");

        jLabel6.setLabelFor(percentField);
        jLabel6.setText("%:");

        jLabel7.setLabelFor(streakField);
        jLabel7.setText("Streak:");

        jLabel8.setLabelFor(ratingCombo);
        jLabel8.setText("Rating:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(videoUrlField, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageUrlField, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageUrlOpenButton)
                            .addComponent(videoUrlOpenButton)))
                    .addComponent(commentField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton))
                            .addComponent(songCombo, 0, 316, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ratingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(streakField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newButton)
                            .addComponent(saveButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(songCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streakField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(imageUrlOpenButton)
                    .addComponent(imageUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(videoUrlOpenButton)
                    .addComponent(videoUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void imageUrlOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageUrlOpenButtonActionPerformed
	if (!imageUrlField.getText().isEmpty()) {
		jshm.util.Util.openURL(imageUrlField.getText());
	}
}//GEN-LAST:event_imageUrlOpenButtonActionPerformed

private void videoUrlOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoUrlOpenButtonActionPerformed
	if (!videoUrlField.getText().isEmpty()) {
		jshm.util.Util.openURL(videoUrlField.getText());
	}
}//GEN-LAST:event_videoUrlOpenButtonActionPerformed

private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_newButtonActionPerformed

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField commentField;
    private javax.swing.JTextField imageUrlField;
    private javax.swing.JButton imageUrlOpenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField percentField;
    private javax.swing.JComboBox ratingCombo;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField scoreField;
    private javax.swing.JComboBox songCombo;
    private javax.swing.JTextField streakField;
    private javax.swing.JTextField videoUrlField;
    private javax.swing.JButton videoUrlOpenButton;
    // End of variables declaration//GEN-END:variables

}
