/*
 * WikiSpPathsFrame.java
 *
 * Created on June 23, 2009, 5:16 PM
 */

package jshm.gui;

import java.awt.GridBagConstraints;
import java.util.List;
import jshm.Difficulty;
import jshm.Instrument.Group;
import jshm.Song;
import jshm.sh.scraper.wiki.SpPathScraper.PathInfo;
import jshm.wt.WtSong;

/**
 *
 * @author  Tim
 */
public class WikiSpPathsFrame extends javax.swing.JFrame {

    /** Creates new form WikiSpPathsFrame */
    public WikiSpPathsFrame() {
        initComponents();
    }

	public void setSong(Song song, Group group, Difficulty diff) {
		setTitle(
			song.getTitle() + " - " +
			song.getActiveGame().title.getWikiAbbr() + " - " +
			group.getLongName(song instanceof WtSong) + " - " +
			diff.getLongName() + " - Wiki SP Paths"
		);
	}
	
	public void addPaths(List<PathInfo> paths) {
		for (PathInfo pi : paths)
			addPath(pi);
		pack();
	}
	
	public void addPath(PathInfo pi) {
		WikiSpPathPanel panel = new WikiSpPathPanel();
		panel.setPathInfo(pi);
		
		GridBagConstraints c = new GridBagConstraints();
		c.gridx = 0;
		c.gridy = GridBagConstraints.RELATIVE;
		c.fill = GridBagConstraints.HORIZONTAL;
		c.weightx = 1.0;
		c.weighty = 0.0;
		pathsPanel.add(panel, c);
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pathsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pathsPanel.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(pathsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WikiSpPathsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pathsPanel;
    // End of variables declaration//GEN-END:variables

}
