/*
 * StatusBar.java
 *
 * Created on August 15, 2008, 4:01 AM
 */

package jshm.gui.components;

import javax.swing.JProgressBar;

/**
 *
 * @author  Tim
 */
public class StatusBar extends javax.swing.JPanel {
	String text = "";
	String lastText = "";
	
    /** Creates new form StatusBar */
    public StatusBar() {
        initComponents();
		setProgressVisible(false);
		setText("");
    }
	
	public void setText(String str) {
		this.lastText = this.text;
		this.text = str;
		
		textLabel.setText(this.text.isEmpty() ? "  " : this.text);
	}
	
	public String getText() {
		return this.text;
	}
	
	public String getLastText() {
		return this.lastText;
	}
	
	public void revertText() {
		this.text = this.lastText;
		this.lastText = "";
		
		textLabel.setText(this.text.isEmpty() ? "  " : this.text);
	}
	
	public JProgressBar getProgressBar() {
		return jProgressBar1;
	}
	
	public void setProgressVisible(boolean value) {
		progSeparator.setVisible(value);
		jProgressBar1.setVisible(value);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topSeparator = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        textLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        progSeparator = new javax.swing.JSeparator();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(topSeparator, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        textLabel.setText("Status text here...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        jPanel1.add(textLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jProgressBar1, gridBagConstraints);

        progSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(progSeparator, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator progSeparator;
    private javax.swing.JLabel textLabel;
    private javax.swing.JSeparator topSeparator;
    // End of variables declaration//GEN-END:variables

}
