/*
 * -----LICENSE START-----
 * JSHManager - A Java-based tool for managing one's ScoreHero account.
 * Copyright (C) 2008, 2009 Tim Mullin
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 * -----LICENSE END-----
*/
/*
 * NotificationBar.java
 *
 * Created on September 3, 2009, 8:42 PM
 */

package jshm.gui.notificationbars;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;

import org.jdesktop.swingx.JXCollapsiblePane;

/**
 *
 * @author  Tim
 */
public class NotificationBar extends JXCollapsiblePane {

    /** Creates new form NotificationBar */
    public NotificationBar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("ToolTip.background"));
        setCollapsed(true);
        getContentPane().setLayout(new java.awt.BorderLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jshm/resources/images/toolbar/close_empty_dark24.png"))); // NOI18N
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setFocusable(false);
        closeButton.setPreferredSize(new java.awt.Dimension(33, 33));
        closeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/jshm/resources/images/toolbar/close24.png"))); // NOI18N
        closeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/jshm/resources/images/toolbar/close24.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

	@Override
	public void setBackground(Color c) {
		super.setBackground(c);
		
		if (null != getContentPane())
			getContentPane().setBackground(c);
	}
	
private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
	setCollapsed(true);
}//GEN-LAST:event_closeButtonActionPerformed

	public javax.swing.JButton getCloseButton() {
		return closeButton;
	}
	
	public Component getMainPanel() {
		return mainPanel;
	}
	
	/**
	 * Collapses the notification bar and removes the main panel.
	 */
	public void removeMainPanel() {
		setCollapsed(true);
		if (null != mainPanel)
			remove(mainPanel);
		mainPanel = null;
	}
	
	public void setMainPanel(Component comp) {
		if (null != mainPanel)
			remove(mainPanel);
		add(comp, BorderLayout.CENTER);
		revalidate();
		setCollapsed(false);
		mainPanel = comp;
	}

	private Component mainPanel = null;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables

}
