/*
 * SelectSongBar.java
 *
 * Created on September 3, 2009, 8:13 PM
 */

package jshm.gui.notificationbars;

import java.util.List;

import javax.swing.JButton;

import jshm.Song;
import jshm.gui.GuiUtil;

/**
 *
 * @author  Tim
 */
public class SelectSongBar extends NotificationBarPanel {
	public SelectSongBar() {
		this(null);
	}
	
    /** Creates new form SelectSongBar */
    public SelectSongBar(List<? extends Song> songs) {
		super();
		
        initComponents();
        
        if (null != songs) {
        	setSongs(songs);
        }
    }

    public void setSongs(List<? extends Song> songs) {
    	GuiUtil.createSongCombo(songCombo, songs);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        songCombo = new javax.swing.JComboBox();
        selectButton = new javax.swing.JButton();

        setOpaque(false);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+3f));
        jLabel2.setText("Select a song:");

        songCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songComboActionPerformed(evt);
            }
        });

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(songCombo, 0, 436, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(selectButton)
                .addComponent(songCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void songComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songComboActionPerformed
if ("comboBoxEdited".equals(evt.getActionCommand())) {
		selectButton.doClick();
	}
}//GEN-LAST:event_songComboActionPerformed

private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed

}//GEN-LAST:event_selectButtonActionPerformed


	public Song getSelectedSong() {
		Object selected = songCombo.getSelectedItem();
		return selected instanceof Song ? (Song) selected : null;
	}

	public JButton getSelectButton() {
		return selectButton;
	}
	
	public void focus() {
		songCombo.requestFocusInWindow();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton selectButton;
    private javax.swing.JComboBox songCombo;
    // End of variables declaration//GEN-END:variables

}
